import {test,expect} from '@playwright/test';
async function create(page,alias){await page.goto('/');await expect(page.locator('#identity')).toContainText('Owner ID:');const me=await (await page.request.get('/api/me')).json();const contract={project_id:alias,goal:'Ship exact synthetic artifact',original_request:'Synthetic browser test only',decision_owner:me.actor,constraints:['No external effects'],tasks:[{id:'one',title:'Synthetic output',dependencies:[],acceptance:[{id:'contains',kind:'file_contains',value:'hello'}]}]};await page.getByText('Create or revise a contract',{exact:true}).click();await page.locator('#contract').fill(JSON.stringify(contract));await page.locator('#create').click();await expect(page.locator('#confirmation')).toBeVisible();await expect(page.locator('#confirm-submit')).toBeEnabled();await page.locator('#confirm-submit').click();await expect(page.locator('#goal')).toHaveText(contract.goal);return (await (await page.request.get('/api/projects')).json()).projects.find(p=>p.alias===alias).project_key;}
async function call(page,name,args){const r=await page.request.post('/mcp',{data:{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}}});expect(r.ok()).toBeTruthy();const value=await r.json();expect(value.result?.isError,JSON.stringify(value)).toBe(false);return value.result.structuredContent;}
test('owner cancels, retries, inspects exact bytes and accepts only the checked revision',async({page})=>{
 const key=await create(page,'browser-main');const session=await call(page,'rumbo_open_worker',{project_key:key,label:'browser test maker'}),args={project_key:key,worker_id:session.worker_id};
 await call(page,'rumbo_claim_task',{...args,task_id:'one',contract_revision:1,lease_seconds:300});await call(page,'rumbo_ingest_artifact',{...args,task_id:'one',contract_revision:1,filename:'test.txt',content:'hello <script>window.bad=true</script>'});await call(page,'rumbo_run_checks',{...args,task_id:'one',contract_revision:1,artifact_revision:1});
 await page.locator('#refresh').click();await page.getByRole('button',{name:'Inspect exact bytes'}).click();await expect(page.locator('#artifact-text')).toHaveText('hello <script>window.bad=true</script>');expect(await page.evaluate(()=>window.bad)).toBeUndefined();await page.locator('#decision-reason').fill('Owner inspected synthetic bytes');await page.locator('#accept').click();await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('#decision-reason')).toHaveValue('Owner inspected synthetic bytes');
 await page.locator('#accept').click();await page.locator('#confirm-submit').click();await expect(page.locator('#tasks')).toContainText('accepted');await page.screenshot({path:'qa-artifacts/owner-accepted-desktop.png',fullPage:true});
 const download=page.waitForEvent('download');await page.locator('#export').click();expect((await download).suggestedFilename()).toBe('rumbo-browser-main-export.ndjson');
 await page.goto('/board?project_key='+key);await expect(page.locator('#goal')).toHaveText('Ship exact synthetic artifact');await expect(page.locator('#accepted-count')).toHaveText('1');await page.locator('#status-filter').selectOption('attention');await expect(page.locator('#list-empty')).toHaveText('No tasks match this filter');await page.screenshot({path:'qa-artifacts/board-filter-desktop.png',fullPage:true});
});
test('mobile owner layout keeps controls in bounds and preserves invalid drafts',async({page})=>{
 await page.setViewportSize({width:390,height:844});await create(page,'browser-mobile');await page.locator('#contract').fill('{invalid');await page.locator('#create').click();await expect(page.locator('#message')).toContainText('draft has been kept');await expect(page.locator('#contract')).toHaveValue('{invalid');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'qa-artifacts/owner-mobile-error.png',fullPage:true});
});
