import {readFileSync,writeFileSync} from 'node:fs';
const entries={OWNER_HTML:'web/owner.html',OWNER_JS:'web/owner.js',OWNER_CSS:'web/owner.css',BOARD_HTML:'web/board.html'};
writeFileSync('worker/assets.js','// Generated by scripts/assets.mjs from reviewed local assets.\n'+Object.entries(entries).map(([key,path])=>'export const '+key+'='+JSON.stringify(readFileSync(path,'utf8'))+';').join('\n')+'\n');
