const $=id=>document.getElementById(id),csrf=document.querySelector('meta[name="rumbo-csrf"]').content;
let projectKey='',state=null,selectedArtifact=null,busy=false,projects=[],unconfirmedDeletion=null;
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';}
async function request(path,options,consume){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
 try{return await consume(await fetch(path,{...options,signal:controller.signal}));}
 catch(error){if(error.name==='AbortError')throw new Error('Request timed out. Refresh to check the latest saved state before retrying.');throw error;}
 finally{clearTimeout(timer);}
}
async function api(path,body){return request(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'content-type':'application/json','x-rumbo-csrf':csrf},...(body===undefined?{}:{body:typeof body==='string'?body:JSON.stringify(body)})},async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;});}
async function run(action){
 if(busy)return;
 const previousFocus=document.activeElement;
 busy=true;document.querySelectorAll('button,#projects').forEach(b=>{if(!b.closest('dialog'))b.disabled=true;});
 try{await action();}catch(e){message(e.message+' Your draft has been kept.',true);}
 finally{
  busy=false;document.querySelectorAll('button,#projects').forEach(b=>b.disabled=false);const project=projects.find(p=>p.project_key===projectKey),unavailable=project?.lifecycle==='deleting'||unconfirmedDeletion?.project_key===projectKey;for(const id of ['revise','grant'])$(id).disabled=unavailable;
  // Disabling the trigger blurs it before a dialog can remember its focus.
  // A just-closed dialog can still own focus when this action settles.
  // Restore only lost focus, never a newer focus choice or a hidden control.
  const active=document.activeElement,focusLost=active===document.body||active?.closest('dialog:not([open])');
  if(focusLost&&previousFocus&&previousFocus!==document.body){
   const target=previousFocus.isConnected&&!previousFocus.closest('[hidden]')?previousFocus:state&&!$('project-panel').hidden?$('goal'):previousFocus.id==='delete-project'&&!projectKey?$('projects'):null;
   target?.focus({preventScroll:true});
  }
 }
}
function confirmAction(title,text,detail){$('confirm-title').textContent=title;$('confirm-text').textContent=text;$('confirm-detail').textContent=detail;const dialog=$('confirmation');dialog.returnValue='';return new Promise(resolve=>{dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true});dialog.showModal();});}
function el(tag,text){const node=document.createElement(tag);node.textContent=text;return node;}
async function loadProjects(){const list=await api('/api/projects');projects=list.projects;const select=$('projects');select.replaceChildren(new Option('Choose a project',''));for(const p of list.projects)select.add(new Option(p.alias+' · '+p.role+(p.lifecycle==='deleting'?' · deletion pending':''),p.project_key));if(projectKey&&!projects.some(p=>p.project_key===projectKey))select.add(new Option('Unavailable project · verify deletion status',projectKey));if([...select.options].some(o=>o.value===projectKey))select.value=projectKey;if(projects.some(p=>p.project_key===projectKey))unconfirmedDeletion=null;}
function clearProjectContent(){state=null;selectedArtifact=null;$('artifact-panel').hidden=true;$('project-panel').hidden=true;$('tasks').replaceChildren();$('artifact-text').textContent='';$('artifact-meta').textContent='';$('goal').textContent='';$('revision').textContent='';$('constraints').textContent='';}
function showDeletion(project){$('privacy-panel').hidden=!['owner','unknown'].includes(project?.role);const pending=project?.lifecycle==='deleting',unknown=project?.lifecycle==='unknown';$('delete-project').textContent=pending?'Continue deletion':unknown?'Retry deletion confirmation':'Delete project';$('delete-status').textContent=pending?'Deletion is pending. Project access is blocked. Continue to retry cleanup; do not assume all content is erased yet.':unknown?'Deletion outcome is unknown. Refresh to check current state, or enter the original project ID and retry the owner-confirmed deletion. Access removal and erasure are not yet confirmed.':'Project ID: '+(project?.alias??'');}
async function loadState(){clearProjectContent();$('privacy-panel').hidden=true;if(!projectKey)return;const project=projects.find(p=>p.project_key===projectKey);if(!project){unconfirmedDeletion??={project_key:projectKey,alias:''};showDeletion({role:'unknown',lifecycle:'unknown'});message('Project unavailable. Deletion outcome is unconfirmed; use the original project ID to verify through the owner deletion flow.');return;}if(project?.lifecycle==='deleting'){showDeletion(project);message('Deletion pending. Continue deletion to retry cleanup.');return;}state=await api('/api/state?project_key='+encodeURIComponent(projectKey));showDeletion(project);$('project-panel').hidden=false;$('goal').textContent=state.goal;$('revision').textContent='Contract revision '+state.contract_revision+' · '+state.tasks.length+' tasks · Owner '+state.decision_owner;$('constraints').textContent=state.constraints.join(' · ');$('board-link').href='/board?project_key='+encodeURIComponent(projectKey);$('tasks').replaceChildren();for(const task of state.tasks){const card=el('div','');card.className='task';card.append(el('h3',task.title),el('p',task.status+(task.stale_reason?' · '+task.stale_reason:'')));if(task.artifact){card.append(el('p','Artifact revision '+task.artifact.revision+' · SHA-256 '+task.artifact.sha256));const inspect=el('button','Inspect exact bytes');inspect.onclick=()=>run(async()=>{const artifact=await api('/api/artifact?project_key='+encodeURIComponent(projectKey)+'&task_id='+encodeURIComponent(task.id)+'&contract_revision='+state.contract_revision+'&artifact_revision='+task.artifact.revision);selectedArtifact={task_id:task.id,contract_revision:artifact.contract_revision,artifact_revision:artifact.artifact_revision};$('artifact-panel').hidden=false;$('artifact-meta').textContent=artifact.filename+' · '+artifact.sha256;$('artifact-text').textContent=artifact.text;$('artifact-panel').scrollIntoView({behavior:'smooth',block:'start'});message('Exact received bytes loaded. Inspect the evidence and record your decision.');});card.append(inspect);}const evidence=el('details','');evidence.append(el('summary','Evidence and decision history'),el('pre',JSON.stringify({acceptance:task.acceptance,evidence:task.evidence,decisions:task.decisions},null,2)));card.append(evidence);$('tasks').append(card);}message('Project refreshed');}
function selectProject(key){if(projectKey!==key){$('delete-confirmation').value='';unconfirmedDeletion=null;}projectKey=key;history.replaceState(null,'',projectKey?'/?project_key='+encodeURIComponent(projectKey):'/');}
$('projects').onchange=()=>run(async()=>{selectProject($('projects').value);await loadState();});
$('refresh').onclick=()=>run(async()=>{await loadProjects();await loadState();});
$('create').onclick=()=>run(async()=>{const raw=$('contract').value;JSON.parse(raw);if(!await confirmAction('Create contract','This records the entire contract as your owner-approved scope.',raw))return;const result=await api('/owner/api/create','{"contract":'+raw+'}');selectProject(result.project_key);await loadProjects();await loadState();});
$('revise').onclick=()=>run(async()=>{if(!state)throw new Error('Choose a project first');const raw=$('contract').value;JSON.parse(raw);const reason=$('change-reason').value;if(!reason.trim())throw new Error('Enter a revision reason');if(!await confirmAction('Revise contract','This changes the agreed scope and invalidates prior acceptance. Expected current revision: '+state.contract_revision,raw+'\nReason: '+reason))return;const prefix=JSON.stringify({project_key:projectKey,expected_revision:state.contract_revision,reason}).slice(0,-1);await api('/owner/api/revise',prefix+',"contract":'+raw+'}');await loadState();});
async function decide(outcome){if(!selectedArtifact)throw new Error('Inspect the exact artifact first');const reason=$('decision-reason').value;if(!reason.trim())throw new Error('Enter a decision reason');const payload={project_key:projectKey,...selectedArtifact,outcome,reason};if(!await confirmAction(outcome==='accepted'?'Accept exact revision':'Reject exact revision','Your decision applies only to the inspected contract/artifact revisions and current evidence.',JSON.stringify(payload,null,2)))return;await api('/owner/api/decide',payload);await loadState();}
$('accept').onclick=()=>run(()=>decide('accepted'));$('reject').onclick=()=>run(()=>decide('rejected'));
$('grant').onclick=()=>run(async()=>{if(!projectKey)throw new Error('Choose a project first');const payload={project_key:projectKey,subject:$('member-subject').value,role:$('member-role').value};if(!await confirmAction('Grant persistent project access','This person will be able to read project records and uploaded bytes. Worker/reviewer roles can also write their permitted records. Confirm the recipient and role.',JSON.stringify(payload,null,2)))return;await api('/owner/api/member',payload);message('Project access updated');});
$('delete-project').onclick=()=>run(async()=>{
 const project=projects.find(p=>p.project_key===projectKey)??(projectKey?{project_key:projectKey,alias:unconfirmedDeletion?.alias??'',role:'unknown',lifecycle:'unknown'}:null);if(!project||!['owner','unknown'].includes(project.role))throw new Error('Choose a project you own');
 const confirmation=$('delete-confirmation').value;if(!/^[A-Za-z0-9][A-Za-z0-9_.-]{0,63}$/.test(confirmation)||(project.alias&&confirmation!==project.alias))throw new Error('Type the exact project ID'+(project.alias?': '+project.alias:''));
 const payload={project_key:projectKey,confirmation};
 if(!await confirmAction(project.lifecycle==='deleting'?'Continue project deletion':'Permanently delete project','This cannot be undone. Export first if you need a copy. This removes all hosted project content and access for every member.',JSON.stringify({project_id:confirmation,project_key:projectKey},null,2)+'\nEmpty hash-derived technical guard keys remain to prevent delayed uploads restoring content. The project ID cannot be reused. Copies already downloaded or held by connected clients, provider backups and logs are not erased by this action.'))return;
 clearProjectContent();unconfirmedDeletion={project_key:projectKey,alias:confirmation};showDeletion({role:project.role,lifecycle:'unknown'});message('Deletion outcome unconfirmed. Waiting for the server response.');
 const result=await api('/owner/api/delete',payload);
 if(result.status==='deleted'){
  projects=projects.filter(p=>p.project_key!==payload.project_key);for(const option of [...$('projects').options])if(option.value===payload.project_key)option.remove();selectProject('');$('projects').value='';$('contract').value='';$('change-reason').value='';$('decision-reason').value='';$('privacy-panel').hidden=true;await loadState();
  const complete='Project content deleted. Empty technical guard keys remain; this project ID cannot be reused. Previously downloaded or provider-held copies are unaffected.';
  try{await loadProjects();message(complete);}catch{message(complete+' The remaining project list could not refresh. Use Refresh to retry.');}
 }else{await loadProjects();await loadState();message('Deletion pending. Project access is blocked. Continue deletion to retry cleanup.');}
});
$('export').onclick=()=>run(async()=>{if(!projectKey)throw new Error('Choose a project first');const blob=await request('/owner/api/export',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','x-rumbo-csrf':csrf},body:JSON.stringify({project_key:projectKey})},async response=>{if(!response.ok)throw new Error((await response.json()).error);return response.blob();});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='rumbo-'+state.project_id+'-export.ndjson';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);message('Export downloaded. Verify it with the included verify-export.py script before relying on it as a backup.');});
await run(async()=>{const me=await api('/api/me');$('identity').textContent='Your Site user ID: '+me.subject+' · Owner ID: '+me.actor;$('contract').value=JSON.stringify({project_id:'my-project',goal:'',original_request:'',decision_owner:me.actor,constraints:[],tasks:[{id:'first-task',title:'',dependencies:[],acceptance:[{id:'check',kind:'file_contains',value:''}]}]},null,2);projectKey=new URLSearchParams(location.search).get('project_key')||'';await loadProjects();await loadState();});
