const $=id=>document.getElementById(id),csrf=document.querySelector('meta[name="rumbo-csrf"]').content;
let projectKey='',state=null,selectedArtifact=null,busy=false;
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';}
async function request(path,options,consume){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);
 try{return await consume(await fetch(path,{...options,signal:controller.signal}));}
 catch(error){if(error.name==='AbortError')throw new Error('Request timed out. Refresh to check the latest saved state before retrying.');throw error;}
 finally{clearTimeout(timer);}
}
async function api(path,body){return request(path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'content-type':'application/json','x-rumbo-csrf':csrf},...(body===undefined?{}:{body:typeof body==='string'?body:JSON.stringify(body)})},async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;});}
async function run(action){if(busy)return;busy=true;document.querySelectorAll('button,#projects').forEach(b=>{if(!b.closest('dialog'))b.disabled=true;});try{await action();}catch(e){message(e.message+' Your draft has been kept.',true);}finally{busy=false;document.querySelectorAll('button,#projects').forEach(b=>b.disabled=false);}}
function confirmAction(title,text,detail){$('confirm-title').textContent=title;$('confirm-text').textContent=text;$('confirm-detail').textContent=detail;const dialog=$('confirmation');dialog.returnValue='';return new Promise(resolve=>{dialog.addEventListener('close',()=>resolve(dialog.returnValue==='confirm'),{once:true});dialog.showModal();});}
function el(tag,text){const node=document.createElement(tag);node.textContent=text;return node;}
async function loadProjects(){const list=await api('/api/projects');const select=$('projects');select.replaceChildren(new Option('Choose a project',''));for(const p of list.projects)select.add(new Option(p.alias+' · '+p.role,p.project_key));if([...select.options].some(o=>o.value===projectKey))select.value=projectKey;}
async function loadState(){state=null;selectedArtifact=null;$('artifact-panel').hidden=true;$('project-panel').hidden=true;if(!projectKey)return;state=await api('/api/state?project_key='+encodeURIComponent(projectKey));$('project-panel').hidden=false;$('goal').textContent=state.goal;$('revision').textContent='Contract revision '+state.contract_revision+' · '+state.tasks.length+' tasks · Owner '+state.decision_owner;$('constraints').textContent=state.constraints.join(' · ');$('board-link').href='/board?project_key='+encodeURIComponent(projectKey);$('tasks').replaceChildren();for(const task of state.tasks){const card=el('div','');card.className='task';card.append(el('h3',task.title),el('p',task.status+(task.stale_reason?' · '+task.stale_reason:'')));if(task.artifact){card.append(el('p','Artifact revision '+task.artifact.revision+' · SHA-256 '+task.artifact.sha256));const inspect=el('button','Inspect exact bytes');inspect.onclick=()=>run(async()=>{const artifact=await api('/api/artifact?project_key='+encodeURIComponent(projectKey)+'&task_id='+encodeURIComponent(task.id)+'&contract_revision='+state.contract_revision+'&artifact_revision='+task.artifact.revision);selectedArtifact={task_id:task.id,contract_revision:artifact.contract_revision,artifact_revision:artifact.artifact_revision};$('artifact-panel').hidden=false;$('artifact-meta').textContent=artifact.filename+' · '+artifact.sha256;$('artifact-text').textContent=artifact.text;$('artifact-panel').scrollIntoView({behavior:'smooth',block:'start'});message('Exact received bytes loaded. Inspect the evidence and record your decision.');});card.append(inspect);}const evidence=el('details','');evidence.append(el('summary','Evidence and decision history'),el('pre',JSON.stringify({acceptance:task.acceptance,evidence:task.evidence,decisions:task.decisions},null,2)));card.append(evidence);$('tasks').append(card);}message('Project refreshed');}
function selectProject(key){projectKey=key;history.replaceState(null,'',projectKey?'/?project_key='+encodeURIComponent(projectKey):'/');}
$('projects').onchange=()=>run(async()=>{selectProject($('projects').value);await loadState();});
$('refresh').onclick=()=>run(async()=>{await loadProjects();await loadState();});
$('create').onclick=()=>run(async()=>{const raw=$('contract').value;JSON.parse(raw);if(!await confirmAction('Create contract','This records the entire contract as your owner-approved scope.',raw))return;const result=await api('/owner/api/create','{"contract":'+raw+'}');selectProject(result.project_key);await loadProjects();await loadState();});
$('revise').onclick=()=>run(async()=>{if(!state)throw new Error('Choose a project first');const raw=$('contract').value;JSON.parse(raw);const reason=$('change-reason').value;if(!reason.trim())throw new Error('Enter a revision reason');if(!await confirmAction('Revise contract','This changes the agreed scope and invalidates prior acceptance. Expected current revision: '+state.contract_revision,raw+'\nReason: '+reason))return;const prefix=JSON.stringify({project_key:projectKey,expected_revision:state.contract_revision,reason}).slice(0,-1);await api('/owner/api/revise',prefix+',"contract":'+raw+'}');await loadState();});
async function decide(outcome){if(!selectedArtifact)throw new Error('Inspect the exact artifact first');const reason=$('decision-reason').value;if(!reason.trim())throw new Error('Enter a decision reason');const payload={project_key:projectKey,...selectedArtifact,outcome,reason};if(!await confirmAction(outcome==='accepted'?'Accept exact revision':'Reject exact revision','Your decision applies only to the inspected contract/artifact revisions and current evidence.',JSON.stringify(payload,null,2)))return;await api('/owner/api/decide',payload);await loadState();}
$('accept').onclick=()=>run(()=>decide('accepted'));$('reject').onclick=()=>run(()=>decide('rejected'));
$('grant').onclick=()=>run(async()=>{if(!projectKey)throw new Error('Choose a project first');const payload={project_key:projectKey,subject:$('member-subject').value,role:$('member-role').value};if(!await confirmAction('Grant persistent project access','This person will be able to read project records and uploaded bytes. Worker/reviewer roles can also write their permitted records. Confirm the recipient and role.',JSON.stringify(payload,null,2)))return;await api('/owner/api/member',payload);message('Project access updated');});
$('export').onclick=()=>run(async()=>{if(!projectKey)throw new Error('Choose a project first');const blob=await request('/owner/api/export',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','x-rumbo-csrf':csrf},body:JSON.stringify({project_key:projectKey})},async response=>{if(!response.ok)throw new Error((await response.json()).error);return response.blob();});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='rumbo-'+state.project_id+'-export.ndjson';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);message('Export downloaded. Verify it with the included verify-export.py script before relying on it as a backup.');});
await run(async()=>{const me=await api('/api/me');$('identity').textContent='Your Site user ID: '+me.subject+' · Owner ID: '+me.actor;$('contract').value=JSON.stringify({project_id:'my-project',goal:'',original_request:'',decision_owner:me.actor,constraints:[],tasks:[{id:'first-task',title:'',dependencies:[],acceptance:[{id:'check',kind:'file_contains',value:''}]}]},null,2);projectKey=new URLSearchParams(location.search).get('project_key')||'';await loadProjects();await loadState();});
